about_widget_content = "TopTens is a fast growing listing site, lists of all you know or don't know. Helps you to choose the best or the worst you are looking for. We you to determine the best video games, greatest songs, hottest celebs, top companies, and more."
address = ""
author = "TopTens"
contact_form_action = "#"
copyright = "All rights reserved by Â© [TheTopTens](https://thetoptens.xyz/)"
custom_script = ""
description = "TopTens is a fast growing listing site, lists of all you know or don't know. Helps you to choose the best or the worst you are looking for. We help you to determine the best video games, greatest songs, hottest celebs, top companies, and more."
email = "contact@thetoptens.xyz"
favicon = "appicons/favicon.ico"
featured_post_title = "Featured Post"
footer_content = "List of top tens for everything you see or don't see !"
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "TopTens Logo"
logo_width = "150x"
mainSections = ["blog"]
mobile = ""
navbar_fixed = false
recent_post_title = "Recent Post"
search = true
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Explore Now"
button_link = "categories/"
content = "We are here to list top ten things of everything you see or know. TopTens provide you the best list on your favorite subject. "
enable = true
image = "images/banner.png"
title_large = "World of **TopTens.**"
title_small = "list of *the best ten* things"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = true
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-facebook"
link = "https://www.facebook.com/TopTensListing"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
