about_widget_content = "Lorem ipsum dolor sit amet, conse tfctetur adipiscing elit. Vel in in donec iaculis tempasus odio nunc laoreet . Libero ullam rgscorper."
address = ""
author = "TopTens"
contact_form_action = "#"
copyright = "All rights reserved By [TopTens](https://toptens.xyz/)"
custom_script = ""
description = "This is meta description"
email = "contact@toptens.xyz"
favicon = "images/favicon.png"
featured_post_title = "Featured Post"
footer_content = "Lorem ipsum dolor sit amt, conse adip iscing. donec iaculis tempasus laoreet. Libero ullam rgscper."
image = "images/logo.png"
logo = "images/logo.png"
logo_text = "TopTens Logo"
logo_width = "150x"
mainSections = ["blog"]
mobile = ""
navbar_fixed = false
recent_post_title = "Recent Post"
search = true
[advertisement]
image = "images/promotion.png"
link = "https://gethugothemes.com/"
[banner]
background_image = "/images/banner-bg-shape.svg"
button_label = "Explore Now"
button_link = "categories/"
content = "We are here to list top ten things of everything you see or know. TopTens provide you the best list on your favorite subject. "
enable = true
image = "images/banner.png"
title_large = "World of **TopTens**"
title_small = "list of the best ten things"
[cookies]
button = "I Accept"
content = "This site uses cookies. By continuing to use this website, you agree to their use."
enable = true
expire_days = 2
[preloader]
enable = false
preloader = ""
[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
[widgets]
sidebar = ["about", "categories", "recent-post", "newsletter"]
[[social]]
icon = "fab fa-facebook"
link = "#"
title = "facebook"
[[social]]
icon = "fab fa-twitter"
link = "#"
title = "twitter"
[[social]]
icon = "fab fa-instagram"
link = "#"
title = "instagram"
[[social]]
icon = "fab fa-github"
link = "#"
title = "github"
[[social]]
icon = "fab fa-linkedin"
link = "#"
title = "linkedin"
